// for dynamic retrieval
library identifier: 'jenkins-devops-libs@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/mschuchard/jenkins-devops-libs.git'])
// if added in Jenkins global config shared libraries
//@Library('jenkins-devops-libs')_
// if added in Jenkins global config shared libraries and the github api plugin is bugging out and slamming github with requests
//library('jenkins-devops-libs')_

pipeline {
  agent { docker { image 'ghcr.io/openfaas/faas-cli:0.18.12' } }

  stages {
    stage('Validate Template') {
      steps {
        sh 'curl -L https://raw.githubusercontent.com/openfaas/faas-cli/master/samples.yml -o /tmp/faas.yaml'

        script {
          faas.validateTemplate('/tmp/faas.yaml')
        }
      }
    }
    stage('Ready') {
      steps {
        script {
          print 'This will fail at runtime without a gateway, but should succeed during compilation.'
          faas.ready(attempts: 1)
        }
      }
    }
    stage('Describe') {
      steps {
        script {
          print 'This will fail at runtime without a gateway, but should succeed during compilation.'
          faas.describe(function: 'echo')
        }
      }
    }
    stage('Logout') {
      steps {
        script {
          print 'This may fail at runtime without a prior login, but should succeed during compilation.'
          faas.logout('http://127.0.0.1:8080')
        }
      }
    }
  }
}
