// for dynamic retrieval
library identifier: 'jenkins-devops-libs@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/mschuchard/jenkins-devops-libs.git'])
// if added in Jenkins global config shared libraries
//@Library('jenkins-devops-libs')
// if added in Jenkins global config shared libraries and the github api plugin is bugging out and slamming github with requests
//library('jenkins-devops-libs')

pipeline {
  agent any

  stages {
    stage('Install') {
      steps {
        script {
          faas.install {
            install_path = '/tmp'
            platform = 'linux'
            version = '0.5.1'
          }
        }
      }
    }
    stage('Validate Template') {
      steps {
        sh 'curl -L https://raw.githubusercontent.com/openfaas/faas-cli/master/samples.yml -o /tmp/faas.yaml'

        script {
          faas.validate_template('/tmp/faas.yaml')
        }
      }
    }
  }
}
