// for dynamic retrieval
library identifier: 'jenkins-devops-libs@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/mschuchard/jenkins-devops-libs.git'])
// if added in Jenkins global config shared libraries
//@Library('jenkins-devops-libs')
// if added in Jenkins global config shared libraries and the github api plugin is bugging out and slamming github with requests
//library('jenkins-devops-libs')

pipeline {
  agent any

  stages {
    stage('Install') {
      steps {
        script {
          packer.install {
            version = '1.1.3'
            install_path = '/tmp'
            platform = 'linux_amd64'
          }
        }
      }
    }
    stage('Plugin Install') {
      steps {
        script {
          packer.plugin_install('https://github.com/YaleUniversity/packer-provisioner-goss/releases/download/v0.3.0/packer-provisioner-goss-v0.3.0-linux-amd64', '/usr/bin/packer-provisioner-goss')
        }
      }
    }
    stage('Validate') {
      steps {
        sh 'curl -L https://raw.githubusercontent.com/mschuchard/jenkins-devops-libs/master/tests/packer/docker.json -o /tmp/docker.json'

        script {
          packer.validate {
            template = '/tmp/docker.json'
          }
        }
      }
    }
    stage('Build') {
      steps {
        script {
          packer.build {
            template = '/tmp/docker.json'
          }
        }
      }
    }
  }
}
