---
version: 2.1

jobs:
  test:
    working_directory: /tmp/project
    docker:
    - image: jenkins/jenkins:lts-slim
    resource_class: small
    steps:
    - checkout
    - restore_cache:
        keys:
        - jenkins-devops-libs
    - run:
        name: install jenkins pipeline and pipeline utility steps plugins
        command: jenkins-plugin-cli -p workflow-aggregator pipeline-utility-steps http_request
    - save_cache:
        paths:
        - /usr/share/jenkins/ref/plugins
        key: jenkins-devops-libs
    - run:
        name: start jenkins server
        command: /opt/java/openjdk/bin/java -jar /usr/share/jenkins/jenkins.war &
    - run:
        name: pause for jenkins startup and then install jenkins cli
        command: sleep 10 && curl localhost:8080/jnlpJars/jenkins-cli.jar -o /var/jenkins_home/war/WEB-INF/lib/jenkins-cli.jar
    - run:
        # TODO: currently jenkins cli does not parse groovysh args correctly
        name: execute syntax check
        command: /opt/java/openjdk/bin/java -jar /var/jenkins_home/war/WEB-INF/lib/jenkins-cli.jar -s http://localhost:8080 -auth admin:$(cat /var/jenkins_home/secrets/initialAdminPassword) 'groovysh -cp src:/usr/share/jenkins:/usr/share/jenkins/ref/plugins -q -e vars/*.groovy'
        no_output_timeout: 45s

workflows:
  execute_tests:
    jobs:
    - test
