// for dynamic retrieval
library identifier: 'jenkins-devops-libs@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/mschuchard/jenkins-devops-libs.git'])
// if added in Jenkins global config shared libraries
//@Library('jenkins-devops-libs')_
// if added in Jenkins global config shared libraries and the github api plugin is bugging out and slamming github with requests
//library('jenkins-devops-libs')_

pipeline {
  agent any

  stages {
    stage('Host Create') {
      steps {
        script {
          awx.host_create(
            description: 'my host', // optional description of the host
            enabled:     true, // optional is host available and online for running jobs
            inventory:   'my_inventory', // ID of the associated inventory
            name:        'foo.bar.com', // name of the host
            variables:   ['foo': 'bar', 'baz': 1], // optional host variables
          )
        }
      }
    }
  }
}
