// for dynamic retrieval
library identifier: 'jenkins-devops-libs@master', retriever: modernSCM(
  [$class: 'GitSCMSource',
   remote: 'https://github.com/mschuchard/jenkins-devops-libs.git'])
// if added in Jenkins global config shared libraries
//@Library('jenkins-devops-libs')_
// if added in Jenkins global config shared libraries and the github api plugin is bugging out and slamming github with requests
//library('jenkins-devops-libs')_

pipeline {
  agent { docker { image 'quay.io/ansible/awx:19.5.1' } }

  environment {
    TOWER_OAUTH_TOKEN = '6E5SXhld7AMOhpRveZsLJQsfs9VS8U'
    TOWER_HOST        = 'awx.svc.cluster.local'
  }

  stages {
    stage('Inventory Create') {
      steps {
        script {
          awx.inventoryCreate(
            description:  'an inventory', // optional description of this inventory
            hostFilter:   'myhosts*', // optional filter that will be applied to the hosts of this inventory
            name:         'my_inventory', // name of this inventory
            organization: 'my_org', // organization containing this inventory
          )
        }
      }
    }
    stage('Inventory Modify') {
      steps {
        script {
          awx.inventoryModify(
            description:  'an inventory', // optional description of this inventory
            hostFilter:   'myotherhosts*', // optional filter that will be applied to the hosts of this inventory
            name:         'my_inventory', // name of this inventory
            organization: 'my_org', // organization containing this inventory
          )
        }
      }
    }
    stage('Host Create') {
      steps {
        script {
          awx.hostCreate(
            description: 'my host', // optional description of the host
            enabled:     true, // optional is host available and online for running jobs
            inventory:   'my_inventory', // ID of the associated inventory
            name:        'foo.bar.com', // name of the host
            variables:   ['foo': 'bar', 'baz': 1], // optional host variables
          )
        }
      }
    }
    stage('Host Delete') {
      steps {
        script {
          awx.hostDelete('foo.bar.com')
        }
      }
    }
    stage('Inventory Delete') {
      steps {
        script {
          awx.inventoryDelete('my_inventory')
        }
      }
    }
    stage('Project Update') {
      steps {
        script {
          awx.projectsUpdate(id: 3)
        }
      }
    }
    stage('Job Template Launch') {
      steps {
        script {
          awx.jobTemplateLaunch(
            extraVars: ['foo': 'bar', 'baz': 1], // optional extra variables
            id:        5, // job template id
            jobType:   'run', // optional job type (run or check)
            skipTags:  ['skipper', 'to_skip'] // optional tags to skip
          )
        }
      }
    }
    stage('Workflow Job Template Launch') {
      steps {
        script {
          awx.workflowJobTemplateLaunch(
            extraVars: ['foo': 'bar', 'baz': 1], // optional extra variables
            id:        2, // job template id
          )
        }
      }
    }
  }
}
