---
name: ci

on:
  push:
    branches: [master]
    paths:
    - '**.groovy'
  pull_request:
    branches: [master]
    paths:
    - '**.groovy'

jobs:
  test:
    runs-on: ubuntu-22.04
    container: jenkins/jenkins:lts-slim # groovy:3.0-jre11
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install jenkins pipeline and pipeline utility steps plugins
      run: jenkins-plugin-cli -p workflow-aggregator pipeline-utility-steps http_request
    - name: execute syntax check
      run: /opt/java/openjdk/bin/java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s http://localhost:8080 groovysh -cp src:/usr/share/jenkins:/usr/share/jenkins/ref/plugins -q vars/*.groovy
